<?php
/**
 * Schéma attendu après exécution complète des migrations (référence pour scan_schema.php).
 * Ajouts uniquement — ne décrit pas les tables legacy supprimées (ex. stock_articles).
 */
return [
    'tables' => [
        'users', 'admin', 'categories', 'produits', 'produits_variantes', 'panier',
        'commandes', 'commande_produits', 'commandes_personnalisees',
        'zones_livraison', 'factures', 'devis', 'devis_produits', 'contacts',
        'clients_b2b', 'bons_livraison', 'bl_lignes', 'factures_mensuelles', 'facture_mensuelle_bl',
        'factures_devis', 'parametres_types_client_bl', 'stock_mouvements',
        'fcm_tokens', 'favoris', 'logos', 'slider', 'videos', 'section4_config', 'trending_config',
        'employes', 'employes_matricules', 'bulletin_paie_parametres',
        'employe_absences', 'employe_absence_justificatifs', 'employe_autorisations_absence',
        'employe_documents', 'employe_prets', 'employe_pret_remboursements', 'employe_sanctions',
        'employe_bulletins_paie', 'employe_conges', 'employe_prime_transport_retraits',
        'livreurs', 'livreur_sessions', 'livreur_positions', 'tracking_watch_tokens',
        'caisse_ventes', 'caisse_vente_lignes', 'factures_personnalisees',
        'user_password_reset', 'admin_password_reset', 'produits_visites',
    ],
    'columns' => [
        ['users', 'accepte_conditions'],
        ['users', 'firebase_uid'],
        ['users', 'auth_provider'],
        ['admin', 'role'],
        ['admin', 'firebase_uid'],
        ['admin', 'auth_provider'],
        ['admin', 'photo_profil'],
        ['commandes', 'zone_livraison_id'],
        ['commandes', 'frais_livraison'],
        ['commandes', 'client_nom'],
        ['commandes', 'livreur_id'],
        ['commandes', 'delivery_latitude'],
        ['commandes', 'tracking_active'],
        ['commandes', 'admin_createur_id'],
        ['commandes', 'admin_dernier_traitement_id'],
        ['commandes', 'mode_livraison'],
        ['commandes', 'delivery_longitude'],
        ['users', 'last_latitude'],
        ['users', 'last_longitude'],
        ['users', 'location_accuracy'],
        ['users', 'location_label'],
        ['users', 'location_updated_at'],
        ['produits', 'couleurs'],
        ['produits', 'taille'],
        ['produits', 'admin_createur_id'],
        ['produits', 'admin_dernier_modificateur_id'],
        ['categories', 'admin_createur_id'],
        ['categories', 'admin_dernier_modificateur_id'],
        ['factures', 'token'],
        ['devis', 'adresse_client'],
        ['devis', 'tva_incluse'],
        ['devis', 'taux_tva_pourcent'],
        ['devis', 'remise_globale_pct'],
        ['devis', 'admin_createur_id'],
        ['bons_livraison', 'adresse_client'],
        ['bons_livraison', 'tva_incluse'],
        ['bons_livraison', 'remise_globale_pct'],
        ['bons_livraison', 'livreur_id'],
        ['bons_livraison', 'numero_reference_fpl'],
        ['bons_livraison', 'facture_bl_payee'],
        ['factures_devis', 'admin_createur_id'],
        ['clients_b2b', 'admin_createur_id'],
        ['contacts', 'adresse'],
        ['contacts', 'plafond_bl_cumul_ht'],
        ['stock_mouvements', 'admin_id'],
        ['tracking_watch_tokens', 'bl_id'],
        ['livreur_positions', 'bl_id'],
        ['employes', 'montant_trimf_mensuel'],
        ['employes', 'matricule'],
        ['commandes_personnalisees', 'image_reference'],
        ['panier', 'variante_id'],
        ['commande_produits', 'nom_produit'],
    ],
];
